# Generated by Django 5.1.3 on 2024-11-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_details', models.TextField()),
                ('about_title', models.CharField(max_length=100)),
                ('about_sub_details', models.TextField()),
                ('about_birthday', models.DateField()),
                ('about_mobile', models.CharField(max_length=15)),
                ('about_city', models.CharField(max_length=15)),
                ('about_age', models.IntegerField()),
                ('about_qualification', models.CharField(max_length=100)),
                ('about_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.TextField()),
                ('contact_mobile', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=100)),
                ('hero_position', models.CharField(max_length=100)),
                ('hero_bgimage', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_details', models.TextField()),
                ('app_image', models.ImageField(upload_to='static/')),
                ('app_title', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='static/')),
                ('product_title', models.CharField(max_length=100)),
                ('gallery_image', models.ImageField(upload_to='static/')),
                ('gallery_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_details', models.TextField()),
                ('resume_summary', models.TextField()),
                ('education_title', models.CharField(max_length=100)),
                ('education_year', models.CharField(max_length=100)),
                ('education_university', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_image', models.ImageField(upload_to='ststic/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonials_details', models.TextField()),
                ('client_review', models.TextField()),
                ('client_image', models.ImageField(upload_to='static/')),
                ('client_name', models.CharField(max_length=100)),
                ('client_position', models.CharField(max_length=100)),
            ],
        ),
    ]
