# Generated by Django 5.1.3 on 2024-11-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_about_about_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image',
            field=models.ImageField(default='', upload_to='static/'),
        ),
    ]
