# Generated by Django 5.1.3 on 2024-11-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_skills_skill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_details',
        ),
    ]
