# Generated by Django 5.1.3 on 2024-11-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_resume_resume_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='project_details2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_name2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
