# Generated by Django 5.1.3 on 2024-11-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_resume_project_details2_resume_project_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_details',
        ),
    ]
