# Generated by Django 5.1.3 on 2024-11-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_portfolio_portfolio_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='testimonials_details',
        ),
    ]
